# -*- coding: utf-8 -*-
"""Copy of Customer churn  prediction24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PmN0ArXBdeaakz0TiBnB6a00lPjjPLFf
"""

# Import library's
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd



df = pd.read_csv("/content/cleaned_telco_churn.csv")

df = pd.read_csv("/content/cleaned_telco_churn.csv")

df.head(10)

df.info()

df.describe()

plt.figure(figsize=(12,6))
sns.heatmap(df.isnull(), cbar=False, cmap="viridis")
plt.title("Missing Values Heatmap")
plt.show()

# plotting the correlation map between the features
plt.figure(figsize=(20,12))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

# Separate Features and Target Variable

X = df.drop("Churn", axis=1)
y = df["Churn"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training Features:", X_train.shape)
print("Testing Features:", X_test.shape)
print("Training Labels:", y_train.shape)
print("Testing Labels:", y_test.shape)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

# Create the Logistic Regression model
lr_model = LogisticRegression()

# Train the model
lr_model.fit(X_train, y_train)

# Make predictions on the test data

y_pred = lr_model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

# Make predictions on the test data

y_pred = lr_model.predict(X_test)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

# Predict on test data
y_pred = lr_model.predict(X_test)

# Display first 10 predictions
print("Predictions:", y_pred[:10])

# Display actual values
print("Actual:", y_test.values[:10])

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

# Predict probabilities
y_prob = lr_model.predict_proba(X_test)[:,1]

# Calculate ROC Curve
fpr, tpr, thresholds = roc_curve(y_test, y_prob)

# Plot ROC Curve
plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label="AUC = %.2f" % roc_auc_score(y_test, y_prob))
plt.plot([0,1], [0,1], 'r--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

from sklearn.tree import DecisionTreeClassifier

# Create the Decision Tree model
dt_model = DecisionTreeClassifier(random_state=42)

# Train the model
dt_model.fit(X_train, y_train)

# Make predictions
y_pred_dt = dt_model.predict(X_test)

from sklearn.metrics import accuracy_score

dt_accuracy = accuracy_score(y_test, y_pred_dt)

print("Decision Tree Accuracy:", dt_accuracy)

from sklearn.ensemble import RandomForestClassifier

# Create the Random Forest model
rf_model = RandomForestClassifier(random_state=42)

# Train the model
rf_model.fit(X_train, y_train)

# Make predictions
y_pred_rf = rf_model.predict(X_test)

from sklearn.metrics import accuracy_score

rf_accuracy = accuracy_score(y_test, y_pred_rf)

print("Random Forest Accuracy:", rf_accuracy)

from sklearn.ensemble import GradientBoostingClassifier

# Create the Gradient Boosting model
gb_model = GradientBoostingClassifier(random_state=42)

# Train the model
gb_model.fit(X_train, y_train)

# Make predictions
y_pred_gb = gb_model.predict(X_test)

# Calculate accuracy
gb_accuracy = accuracy_score(y_test, y_pred_gb)

print("Gradient Boosting Accuracy:", gb_accuracy)

import pandas as pd

comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "Gradient Boosting"
    ],
    "Accuracy": [
        accuracy,
        dt_accuracy,
        rf_accuracy,
        gb_accuracy
    ]
})

comparison

comparison = comparison.sort_values(by="Accuracy", ascending=False)

print(comparison)

# Find the best model
best_model = comparison.loc[comparison["Accuracy"].idxmax()]

print("Best Model:", best_model["Model"])
print("Accuracy:", best_model["Accuracy"])

new_customer = [[1, 0, 0, 45, 1, 70.5, 3500]]

print(X.shape)

print(len(X.columns))

print(X.columns)

print(new_customer)

print(len(new_customer))

print(len(new_customer[0]))

new_customer = X_test[:1]
prediction = lr_model.predict(new_customer)
print(prediction)

"""




Customer Churn Prediction - Project Summary

Objective
The goal of this project was to predict whether a customer is likely to churn using machine learning classification models.

Models Used
Logistic Regression

Decision Tree Classifier

Random Forest Classifier

Gradient Boosting Classifier

Model Comparison
Model   Accuracy
Logistic Regression 81.97%
Gradient Boosting   80.91%
Random Forest   79.91%
Decision Tree   71.54%
Best Model
Logistic Regression achieved the highest accuracy (81.97%) and was selected as the final model.

Conclusion
This model can help businesses identify customers who are likely to leave so they can take actions to improve customer retention."""